### ISSUE TITLE
op路由上运行提示认证错误

### ISSUE THREAD

**Issue by xuefliang** [dosgo/ngrok-php#7]
cgi模式op路由上运行提示认证错误，在ubuntu正常！

**Comment by dosgo** [comment]
参数一样?服务器一样?错误截图呢?

**Comment by xuefliang** [comment]
![img_20170102_123910](https://cloud.githubusercontent.com/assets/3095597/21584612/fac0fd90-d0e8-11e6-98f3-50b34543090c.jpg)

**Comment by dosgo** [comment]
不支持那个服务器，你用python版本把，就是另一个大神写的
